### ISSUE TITLE
Create the main menu

### ISSUE THREAD

**Issue by AndreasLrx** [MisterPeModder/Bomberman-Global-Offensive#59]
Create a main menu linked to:
- [x] Game
- [ ]  Options
- [x] Quit

Players must be able to join on this menu, characters must be configurable here.

**Comment by francoisbaudouin** [comment]
linked issue to #9

**Comment by francoisbaudouin** [comment]
Program started with a "splash-stream"(during 2-5 seconds), You can skip it with any  key.

**Comment by francoisbaudouin** [comment]
On main menu, 

On left side, a column contains buttons : 
- Start game
- Option
- logout

Main screen contain fourth "player". Users can joins pressing a specific key and selecting/creating their own profile. However, is possible to set an AI instead of a player and choose their difficulties. 

After connection, players have a possibility to choose a skin by clicking the arrow on either side of the character

Background is animated.
